include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unnecessary_this: ignore
    prefer_final_fields: ignore
    avoid_function_literals_in_foreach_calls: ignore

linter:
  rules:
    avoid_print: false
    use_build_context_synchronously: false
    use_super_parameters: false
    library_private_types_in_public_api: false