# .github/workflows/quality_check.yml
name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest # O 'macos-latest' si desarrollas para iOS también

    steps:
      - uses: actions/checkout@v3 # Paso para obtener tu código

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Es CRUCIAL que esta versión de Flutter proporcione un SDK de Dart
          # compatible con la versión requerida por tu pubspec.yaml (tu proyecto pide ^3.7.2).
          # Flutter 3.22.0 viene con Dart 3.10.x, lo cual es compatible.
          flutter-version: '3.22.0' # ¡Actualizado a una versión más reciente!
          channel: 'stable'       # Asegura que se use la rama estable

      - name: Verify Dart SDK Version # Paso de depuración: verifica la versión de Dart SDK
        run: dart --version

      - name: Install dependencies
        # Este paso ejecutará 'flutter pub get'.
        # Si aún hay problemas aquí, significa que la versión de Dart SDK
        # del runner sigue siendo incompatible o hay un conflicto de paquetes en pubspec.yaml
        # que no has resuelto localmente (como el anterior de 'intl').
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test