# .github/workflows/quality_check.yml
name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest # O 'macos-latest' si desarrollas para iOS también

    steps:
      - uses: actions/checkout@v3 # Paso para clonar tu repositorio

      - name: Set up Flutter # Configura el entorno de Flutter
        uses: subosito/flutter-action@v2
        with:
       
          flutter-version: '3.32.5' 
         

      - name: Verify Dart SDK Version # ¡CRUCIAL PARA DEPURAR!
        run: dart --version 

      - name: Install dependencies 
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests 
        run: flutter test